---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  TwitterConsumerKey:
    Type: String

  TwitterConsumerSecret:
    Type: String

  TwitterAccessToken:
    Type: String

  TwitterAccessTokenSecret:
    Type: String

Resources:
  ConsumerKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: TwitterConsumerKey
      Name: TwitterConsumerKey
      SecretString:
        !Ref TwitterConsumerKey

  ConsumerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: TwitterConsumerSecret
      Name: TwitterConsumerSecret
      SecretString:
        !Ref TwitterConsumerSecret

  AccessToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: TwitterAccessToken
      Name: TwitterAccessToken
      SecretString:
        !Ref TwitterAccessToken

  AccessTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: TwitterAccessTokenSecret
      Name: TwitterAccessTokenSecret
      SecretString:
        !Ref TwitterAccessTokenSecret
